FROM python:3.9-slim

WORKDIR /usr/src/app

RUN pip install --upgrade pip
COPY requirements-mlflow.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

CMD mlflow server \
  --backend-store-uri ${BACKEND_URI} \
  --default-artifact-root ${ARTIFACT_ROOT} \
  --host 0.0.0.0
