FROM python:3.9-slim

RUN pip install --upgrade pip
COPY requirements-jupyter.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# RUN apt-get update && apt-get install -y git

WORKDIR /notebook

EXPOSE 8888

CMD jupyter lab --allow-root